### ISSUE TITLE
Wallpaper request

### ISSUE THREAD

**Issue by msr8** [DawidWK/conky-simple-clock#1]
Could I get the wallpaper please?

**Comment by DawidWK** [comment]
I no longer have it, but this is what i found. It's the same but much darker, you can try 
brighten it up, or find orginal with google image search. 

https://www.wallpaperflare.com/dark-minimalism-cherry-trees-sunset-mountain-night-sky-no-people-wallpaper-hcdyl/download

If you somehow find it, drop it here please :)

**Comment by DawidWK** [comment]
@msr8

**Comment by msr8** [comment]
Thank you for the response! Here are some similar ones I found:

![image](https://github.com/DawidWK/conky-simple-clock/assets/79649185/d820b8e9-68aa-46e6-acd7-a105dbe9df31)

![image](https://github.com/DawidWK/conky-simple-clock/assets/79649185/ee2a3138-9198-4e71-8bf9-2502e3829941)

![image](https://github.com/DawidWK/conky-simple-clock/assets/79649185/bafe0b85-cd39-4f47-b187-ec9525e5763f)

![image](https://github.com/DawidWK/conky-simple-clock/assets/79649185/9207f3b3-e0a5-4ddb-8ca1-750d5d63fa0a)

Here is the full tineye search if you wanna go through more variations: https://tineye.com/search/f3a750696b277addfbdb1054f30598b3ecdaa9bd?sort=score&order=desc
